# Website settings
url: "https://dmikushin.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Dmitry Mikushin"
description: "The home page of Dmitry Mikushin, GPU&amp;HPC engineer, co-founder of Purple Gaze Inc."
thumbnail_path: "profile-photos/picture.jpg"
purplegaze_url: "https://purplegaze.io/"
apcllc_repo_url: "https://parallel-computing.pro/"
unil_url: "https://www.unil.ch/hec-phd/en/home/menuinst/programs/phd-in-business-analytics/current-students.html"
website_repo_url: "https://github.com/dmikushin/homepage"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/dmikushin/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/dmikushin/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:dmitry@kernelgen.org"
    label: "Email"
    value: "dmitry@kernelgen.org"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Geneva'
repository: dmikushin/homepage

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
